[package]
name = "pipit-gbc"
description = "Game Boy / Game Boy Color emulation core: no I/O, no platform code"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
pipit-common = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
